import { Icon } from "@react-native-material/core"
import { ReactNode } from "react"

type TextSegment = {
  text: string,
  bold?: boolean,
  italic?: boolean,
  color?: string,
  icon?: ReactNode,
}

const tourTextData: { [key: string]: TextSegment[] } = {
  homeScreenModalText: [
    { text: 'Welcome to the ' },
    { text: 'Home Screen', bold: true },
    { text: '.\n\n' },
    { text: 'This is the default screen of the application.\n\n' },
    { text: 'From this screen you can:\n' },
    { text: '-  View your active programs\n', bold: true },
    { text: '-  Check your weekly progress\n', bold: true },
    { text: '-  Browse all available\n   programs or exercises', bold: true },
  ],
  programsListScreenModalText: [
    { text: 'This is the ' },
    { text: 'Program Browser', bold: true },
    { text: '.\n\n' },
    { text: 'Here you can view and subscribe to any of the available programs.\n\n' },
    { text: 'You can sort programs by\n' },
    { text: '- Type (orientation)\n', bold: true },
    { text: '- Completion difficulty', bold: true },
  ],
  hubScreenModalText: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  activeSessionScreenModalText: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  endSessionScreenModalText: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText1: [
    { text: "Let's start by browsing existing programs." },
  ],
  copilotStepText2: [
    { text: 'This is one of the program cards.\n\n' },
    { text: "Let's " },
    { text: 'Subscribe', color: 'green', bold: true },
    { text: ' to it.' },
  ],
  copilotStepText3: [
    { text: "Here is where you will see all currently active programs that you've subscribed to.\n\n" },
    { text: 'If you want to create a custom program, you can press ', icon: <Icon name="plus" size={20} color="#121212" /> },
    { text: ' in the top right corner.\n\n' },
    { text: 'Notice that ' },
    { text: 'Your First Exercise Program', bold: true },
    { text: ' now appears in the list of the Active Programs.' },
  ],
  copilotStepText4: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText5: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText6: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText7: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText8: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText9: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText10: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
}

export default tourTextData
