import { Icon } from "@react-native-material/core"
import { ReactNode } from "react"

type TextSegment = {
  text: string,
  bold?: boolean,
  italic?: boolean,
  color?: string,
  icon?: ReactNode,
}

const tourTextData: { [key: string]: TextSegment[] } = {
  homeScreenModalText: [
    { text: 'Welcome to the ' },
    { text: 'Home Screen', bold: true },
    { text: '.' },
    { text: '' },
    { text: 'This is the default screen' },
    { text: 'of the application.' },
    { text: '' },
    { text: 'From this screen you can:' },
    { text: '- View your active programs', bold: true },
    { text: '- Check your weekly status       ', bold: true },
    { text: '- ', bold: true },
    { text: 'Browse all programs and exercises', bold: true },
  ],
  programsListScreenModalText: [
    { text: "Let's start by subscribing to an existing program" },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  hubScreenModalText: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  activeSessionScreenModalText: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  endSessionScreenModalText: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText1: [
    { text: "Let's start by browsing existing programs." },
  ],
  copilotStepText2: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText3: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText4: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText5: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText6: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText7: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText8: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText9: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
  copilotStepText10: [
    { text: 'This is ' },
    { text: 'bold', bold: true },
    { text: ' text, ' },
    { text: 'italic', italic: true },
    { text: ' text, ' },
    { text: 'colored', color: 'green' },
    { text: ' text, and ' },
    { text: 'text with an icon ', icon: <Icon name="rocket" size={20} color="#121212" /> },
  ],
}

export default tourTextData
